# GoReleaser configuration for SpellingClash
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download

builds:
  - id: spellingclash
    main: ./cmd/server
    binary: spellingclash
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Override CC for cross-compilation
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_ENABLED=1
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
          - CGO_ENABLED=1

dockers:
  - image_templates:
      - "ghcr.io/sammcgeown/spellingclash:{{ .Version }}-amd64"
      - "ghcr.io/sammcgeown/spellingclash:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    skip_push: true
    ids:
      - spellingclash
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=SpellingClash"
      - "--label=org.opencontainers.image.description=A spelling practice app for kids"
      - "--label=org.opencontainers.image.url=https://github.com/sammcgeown/spellingclash"
      - "--label=org.opencontainers.image.source=https://github.com/sammcgeown/spellingclash"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: amd64
    extra_files:
      - internal/templates
      - static
      - migrations
      - data

  - image_templates:
      - "ghcr.io/sammcgeown/spellingclash:{{ .Version }}-arm64"
      - "ghcr.io/sammcgeown/spellingclash:latest-arm64"
    use: buildx
    dockerfile: Dockerfile
    skip_push: true
    ids:
      - spellingclash
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=SpellingClash"
      - "--label=org.opencontainers.image.description=A spelling practice app for kids"
      - "--label=org.opencontainers.image.url=https://github.com/sammcgeown/spellingclash"
      - "--label=org.opencontainers.image.source=https://github.com/sammcgeown/spellingclash"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: arm64
    extra_files:
      - internal/templates
      - static
      - migrations
      - data

docker_manifests:
  - name_template: "ghcr.io/sammcgeown/spellingclash:{{ .Version }}"
    image_templates:
      - "ghcr.io/sammcgeown/spellingclash:{{ .Version }}-amd64"
      - "ghcr.io/sammcgeown/spellingclash:{{ .Version }}-arm64"

  - name_template: "ghcr.io/sammcgeown/spellingclash:latest"
    image_templates:
      - "ghcr.io/sammcgeown/spellingclash:latest-amd64"
      - "ghcr.io/sammcgeown/spellingclash:latest-arm64"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - internal/templates/**/*
      - static/**/*
      - migrations/**/*
      - data/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "sammcgeown"
    name: spellingclash
  prerelease: auto
