# GoReleaser configuration for SpellingClash
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download

builds:
  - id: spellingclash
    main: ./cmd/server
    binary: spellingclash
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Override CC for cross-compilation
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_ENABLED=1
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
          - CGO_ENABLED=1
    # Skip Linux CGO builds in snapshot/local mode
    skip: '{{ .IsSnapshot }}'
  
  - id: spellingclash-local
    main: ./cmd/server
    binary: spellingclash
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Only build in snapshot/local mode
    skip: '{{ not .IsSnapshot }}'

dockers_v2:
  - images:
      - ghcr.io/sammcgeown/spellingclash
    dockerfile: Dockerfile.goreleaser
    ids:
      - spellingclash
    tags:
      - "{{ .Version }}"
      - latest
    labels:
      org.opencontainers.image.title: SpellingClash
      org.opencontainers.image.description: A spelling practice app for kids
      org.opencontainers.image.url: https://github.com/sammcgeown/spellingclash
      org.opencontainers.image.source: https://github.com/sammcgeown/spellingclash
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: false
    extra_files:
      - internal/templates
      - static
      - migrations
      - data

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - internal/templates/**/*
      - static/**/*
      - migrations/**/*
      - data/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "sammcgeown"
    name: spellingclash
  prerelease: auto
